[supervisord]
nodaemon=true
logfile=/var/log/supervisor.log
pidfile=/var/run/supervisord.pid

[program:gunicorn]
command=/usr/local/bin/gunicorn --bind 127.0.0.1:8000 --workers 3 --timeout 120 config.wsgi:application
directory=/app
user=root
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/gunicorn.log
environment=DB_NAME="autosale",DB_USER="postgres",DB_PASSWORD="postgres",DB_HOST="db",DB_PORT="5432",SECRET_KEY="django-insecure",ALLOWED_HOSTS="*"

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
directory=/etc/nginx
user=root
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/nginx.log
