# Generated by Django 5.0.3 on 2026-03-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/%Y/%m/%d/', verbose_name='Основное фото'),
        ),
    ]
